name: Deploy
on:
  push:
    branches: [ main ]   # despliega al hacer push a main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}  # verifica el nombre EXACTO
        run: |
          flyctl deploy --remote-only --strategy rolling
